apiVersion: v1
kind: Namespace
metadata:
  name: semesta

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: semesta-app1
  namespace: semesta
  labels:
    name: semesta-app1
spec:
  replicas: 4
  selector:
    matchLabels:
      name: semesta-app1
  template:
    metadata:
      name: semesta-app1
      labels:
        name: semesta-app1
    spec:
      containers:
        - name: semesta-app1
          image: unvizy/s-app1:tagversion
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "128Mi"
              cpu: "300m"

---
apiVersion: v1
kind: Service
metadata:
  name: semesta-app1-service
  namespace: semesta
spec:
  selector:
    name: semesta-app1
  ports:
    - port: 80
      targetPort: 3000



---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: unvizy-ssl
  namespace: semesta
spec:
  domains:
    - semesta.unvizy.xyz

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: semesta-ingress
  namespace: semesta
  annotations:
    kubernetes.io/ingress.global-static-ip-name: semesta-ip
    kubernetes.io/ingress.allow-http: "false"
    networking.gke.io/managed-certificates: unvizy-ssl
  labels:
    name: semesta-ingress
spec:
  rules:
  - host: semesta.unvizy.xyz
    http:
      paths:
      - path: "/*"
        pathType: ImplementationSpecific
        backend:
          service:
            name: semesta-app1-service
            port: 
              number: 80

                       