apiVersion: v1
kind: Namespace
metadata:
  name: semesta

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: semesta-app2
  namespace: semesta
  labels:
    name: semesta-app2
spec:
  replicas: 2
  selector:
    matchLabels:
      name: semesta-app2
  template:
    metadata:
      name: semesta-app2
      labels:
        name: semesta-app2
    spec:
      containers:
        - name: semesta-app2
          image: unvizy/s-app2:tagversion
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-semesta-app2
  namespace: semesta
spec:
  maxReplicas: 5
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: semesta-app2
  targetCPUUtilizationPercentage: 100

---
apiVersion: v1
kind: Service
metadata:
  name: semesta-app2-service
  namespace: semesta
spec:
  selector:
    name: semesta-app2
  ports:
    - port: 80
      targetPort: 3000



                       